# Site settings
lang: zh-CN
timezone: Asia/Shanghai
url: "https://yqlizeao.55555.io"
baseurl: ""
title: 胶卷的缤纷世界
tagline: 胶卷印象的博客 | Leo Blog
description: "Game Developer，热爱渲染，希望自己也能写出绚丽的特效"

# Author
author:
  name: Leo
  avatar: /img/touxiang.jpg
  bio: "用心积累，成长进步。学习是一辈子的事情。"
  location: China
  links:
    - label: Email
      url: mailto:yqlizeao@foxmail.com
      icon: fas fa-envelope
    - label: GitHub
      url: https://github.com/yqlizeao
      icon: fab fa-github
    - label: Weibo
      url: https://weibo.com/yqlizeao
      icon: fab fa-weibo
    - label: Zhihu
      url: https://www.zhihu.com/people/yqlizeao
      icon: fab fa-zhihu
    - label: Twitter
      url: https://twitter.com/yqlizeao
      icon: fab fa-twitter

# Theme
theme: jekyll-theme-chirpy

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

feed:
  path: atom.xml

# Pagination
paginate: 10
paginate_path: /page:num/

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "_tabs"
      type: tabs
    values:
      layout: page

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Social preview
social:
  name: Leo
  links:
    - https://github.com/yqlizeao

# Analytics
google_analytics:
  id: UA-106151904-1
  anonymize_ip: false

# Exclude
exclude:
  - README.zh.md
  - node_modules
  - vendor
